### ISSUE TITLE
Can u make hhvm for centos 6 as well? 

### ISSUE THREAD

**Issue by hwongcom** [no1youknowz/hhvm-repo#4]
Thanks

**Comment by jrobeson** [comment]
doing builds for centos takes a really long time, and a lot of work. None of us use centos 6 in production, so we'll never be able to do it.

**Comment by no1youknowz** [comment]
I suggest going to freenode irc and the #hhvm channel.  There are some guys running Centos 6.  I would ask them on instructions on getting it to install.
