### ISSUE TITLE
/usr/lib64/hhvm/extensions/geoip.so was built for HHVM 3.7

### ISSUE THREAD

**Issue by cmorland** [no1youknowz/hhvm-repo#6]
Jun 17 11:22:43 localhost systemd: Starting HipHop Virtual Machine (FCGI)...
Jun 17 11:22:43 localhost systemd: Started HipHop Virtual Machine (FCGI).
Jun 17 11:22:43 localhost hhvm: Uncaught exception: /usr/lib64/hhvm/extensions/geoip.so was built for HHVM 3.7, and cannot be loaded with HHVM 3.8\n
Jun 17 11:22:43 localhost systemd: hhvm.service: main process exited, code=exited, status=255/n/a
Jun 17 11:22:43 localhost systemd: Unit hhvm.service entered failed state.

rpm -qa |grep hhvm
hhvm-3.8.0-1.el7.centos.x86_64
hhvm-ext-geoip-1.1.0-1.el7.centos.x86_64

**Comment by no1youknowz** [comment]
I saw this on my dev box, but haven't had time to resolve.  Simple enough to do.

I'll update the ticket when this is resolved.

**Comment by no1youknowz** [comment]
I think it's resolved now.  I havent had time to test it tho.

However, my experience with HHVM isn't going to well.  I have removed the prebuild package from HHVM.

I am unable to support this.  

I suggest building/compiling this yourself or if you need support use ubuntu.

I am closing the ticket.
